<?php

use App\Models\Course;
use App\Models\CourseCategory;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        factory(App\Models\Course::class, 50)->create();

        $courses = [
            [
                'name' => 'Introduction to VueJS',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),

            ],
            [
                'name' => 'Introduction to Big Data',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Introduction to Laravel',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Introduction to Angular',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Introduction to HTML',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Network and Security',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Hardware',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Software Development',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Software Tools',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'IT Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Mobile Apps',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Software Engineering',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Data Science',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Databases',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Core IT Skills',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Core IT Skills',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Spanish',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'German',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Irish',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'French',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Chinese',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Arabic',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Swedish',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Japanese',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Life Science',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Physics',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Chemistry',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Engineering',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Mental Health',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Health Care',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Nutrition',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Fitness',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Yoga',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Core Maths Skills',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Calculus',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Probability and Statistics',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Algebra',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Geometry',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Series and Sequences',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Exam Prep',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Food and Beverage',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Art and Crafts',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Literature',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Exam Prep',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Photography',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Skilled Trades',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Front End Technologies',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Back End Languages',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Software Testing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],


            [
                'name' => 'Social Media Marketing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Marketing Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Digital Marketing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Public Relations',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Finances and Banking',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Accounting',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Supply Chain Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Business Process Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Risk Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Service Management',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Management and Administration',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Customer Service',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Manufacturing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Health and Safety',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Quality Control',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Workplace Supervision',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],

            [
                'name' => 'Plumbing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Electrical',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Plumbing',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Carpentry',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Masonry',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ],
            [
                'name' => 'Motor',
                'description' => '',
                'category_id' => array_random(CourseCategory::all()->pluck('id')->toArray()),
                'user_id' => array_random(User::all()->pluck('id')->toArray()),
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now(),
            ]
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }

    }
}
